#!/usr/bin/env python3
"""Emit the Make variables for the MosaicRV p0 firmware corpus.

    python3 mkvars.py --emit-make

Reads tests/programs/corpus.json -- the single source of truth for which
programs exist and which three inputs each one runs with -- and writes a
Makefile fragment naming every ELF to build and the -DPROG_INPUTn values
each one must be compiled with.

The fragment is included by tests/programs/Makefile so that adding a
(program, input) pair to corpus.json is the only edit needed to extend the
build.  Nothing here interprets firmware.
"""

from __future__ import annotations

import json
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
CORPUS = os.path.join(HERE, "corpus.json")


def load() -> dict:
    with open(CORPUS) as handle:
        return json.load(handle)


def emit_make(document: dict) -> str:
    names = [program["name"] for program in document["programs"]]
    lines = [
        "# Generated by mkvars.py from corpus.json.  Do not edit by hand.",
        "PROGRAMS := " + " ".join(names),
        "",
    ]
    for program in document["programs"]:
        for index, entry in enumerate(program["inputs"]):
            elf = "build/%s.i%d.elf" % (program["name"], index)
            lines.append("%s: PROG_INPUT0 := %s" % (elf, entry["a"]))
            lines.append("%s: PROG_INPUT1 := %s" % (elf, entry["b"]))
            lines.append("%s: PROG_INPUT2 := %s" % (elf, entry["c"]))
    lines.append("")
    return "\n".join(lines)


def elf_list(document: dict) -> list:
    result = []
    for program in document["programs"]:
        for index in range(len(program["inputs"])):
            result.append("build/%s.i%d.elf" % (program["name"], index))
    return result


def main(argv: list) -> int:
    if len(argv) != 1:
        sys.stderr.write("usage: mkvars.py --emit-make\n")
        return 2
    document = load()
    if argv[0] == "--emit-make":
        sys.stdout.write(emit_make(document))
        return 0
    sys.stderr.write("unknown option %r\n" % (argv[0],))
    return 2


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))