// ============================================================================
// mosaic_remote_link -- work package I-028.
//
// The transport that carries one uop from its home cluster to a remote
// cluster's functional unit and brings the result back. It is a leaf: there is
// no consumer in the core yet, so the interior of the module is this file's
// decision, and every number in it is derived from a generated package.
//
// ------------------------------------------------------- what this module owns
//
// Three pieces of state, and nothing else:
//
//   1. `entry_valid/id/dst[0:ENTRIES-1]`  the *pairing table*: one entry per
//      request the link has taken responsibility for.
//   2. `req_pipe[0:LATENCY-1]`            the request hop, home  -> remote.
//   3. `rsp_pipe[0:LATENCY-1]`            the response hop, remote -> home.
//
// plus counters, so that the credit accounting is checkable from the `o_*`
// ports rather than only from the testbench's own model.
//
// ------------------------------------------------ why a pairing table, and its bound
//
// A response must be delivered to the *request that produced it*, and the
// link must be able to decide that without knowing anything about the core.
// So the link allocates its own name for each request -- a **link id**, the
// index of the entry it took -- and the request carries that name to the
// remote unit, which echoes it on the response. The table then answers the
// question in one step: `entry_valid[lid]` says whether the request that owns
// that name is still the link's responsibility.
//
// The link id alone is not enough, and the second half of the mechanism is why
// this module exists as a separate work package. A link id is an *index*, and
// an index is recycled: a killed request's entry is handed to the next request
// within a cycle or two, so a response that arrives late carries the link id of
// a request that has nothing to do with it. What makes that late response
// recognisable is the **identity** carried in the payload -- the uop's
// `{hart, rob_index, rob_gen, uop_index}` from `mosaic_id_pkg`, plus the
// destination `{tag, gen}`. The response is accepted only when the link id
// names a live entry *and* that entry's stored identity and destination are the
// ones the response carries. A response that fails either test is dropped and
// counted (`o_stale_rsp_ctr`), and the entry it named -- if any -- is untouched.
//
// This is the "tagged completion" shape the plan's I-002 contract requires: a
// wrapping index (the link id) is never the identity by itself, and the
// generation in the identity is what distinguishes the new occupant of a slot
// from the old one. It is the same rule `mosaic_rename` applies to a recycled
// physical tag, applied one level up.
//
// **Bound.** `ENTRIES = MOSAIC_IQ_ENTRIES` -- the depth of one cluster's issue
// queue. The justification is not "8 is a nice number": a remote request
// occupies a slot in the destination cluster's issue queue from the moment it
// is accepted until its result has left that cluster, so the number of requests
// one home cluster can have in flight to one remote cluster cannot exceed that
// queue's depth. Sizing the pairing table to exactly that bound means the link
// is never the *first* structure to run out of room: when the table is full,
// the destination queue is full too, and the back-pressure the home side sees
// is the one the far end would have applied anyway. It also fixes the width of
// the link id at `$clog2(ENTRIES)`, which is what makes the table a direct
// lookup rather than a search.
//
// ------------------------------------------------ the credit and what is conserved
//
// One table entry is one credit. A credit is taken when a request is accepted
// (`o_issued_ctr`) and returned exactly once when the entry is released, either
// because the response matched it (`o_matched_ctr`) or because the home side
// killed it (`o_killed_ctr`, which also covers the bulk `flush_valid`). The
// link therefore maintains
//
//     o_issued_ctr == o_returned_ctr + o_outstanding
//
// as an invariant of every cycle, reset included, and the counters are
// generated by the same events that move the table. `o_outstanding` is also
// registered *independently* of the bitmap, so the testbench can check both
// that the counter equals the population of `o_entry_valid` and that the
// conservation law holds -- a defect in either the table or the counter is
// visible without trusting the other.
//
// The returned credit is `o_returned_ctr = o_matched_ctr + o_killed_ctr`.
//
// A response that is dropped must also consume its credit, or the dropped
// response's entry would stay live forever: that is why a rejection is
// *counted* and not merely ignored. Only a response that is actually matched
// frees an entry, so a stale response cannot mask a live one.
//
// --------------------------------------------------------------- kill and flush
//
// `kill_valid` names one identity and `flush_valid` names all of them. Both are
// resolved against the pre-edge table, so a kill can never free an entry that a
// request is allocating in the same cycle (an allocation only ever considers an
// entry that is already invalid, and a freed entry is still valid until the
// edge). One cycle of extra back-pressure, in exchange for "released exactly
// once" being structural rather than argued.
//
// **A kill outranks a same-cycle response match for the same entry.** If both
// name the same entry, the home side has just told the link the uop is dead, so
// the response is dropped and counted like any other late response and the kill
// returns the credit. The alternative -- delivering a result for an instruction
// the home side has this cycle declared dead -- would make the home responsible
// for discarding it a second time, and would make "the killed request's
// resources are returned exactly once" depend on which of two simultaneous
// events the implementation happened to prefer.
//
// A kill does **not** withdraw the request from the network. The request may
// already have been handed to the remote unit, and a packet in flight cannot be
// recalled; the remote unit will do the work and answer, and the answer will be
// dropped as stale. That is what the case `remote.kill_with_delayed_response`
// exercises.
//
// -------------------------------------------------------- the two independent hops
//
// Each direction is its own registered pipeline of `LATENCY` stages, and the
// two share no payload storage, no valid/ready signal and no finite resource
// other than the credit table. `rem_req_valid` and `rsp_valid` are functions of
// registers alone (the link is a genuine registered hop in both directions);
// `req_ready` and `rem_rsp_ready` are the two ready signals, and each depends
// only on its own pipeline plus the far side of *its own* channel.
//
// The pipeline is a shift register with a **global stall**: the whole pipe
// advances by one stage each cycle unless its output stage holds an item the
// far side has not accepted. Two consequences are deliberate:
//
//   * The delay is a property of the link, not of the occupancy pattern: an
//     accepted request is offered to the remote end exactly `LATENCY` cycles
//     later, and every item in the pipe is delayed by the same stall. A
//     bubble-collapsing (fully elastic) pipeline would be cheaper in buffer
//     occupancy and would make the arrival time depend on the pattern of
//     bubbles in front of it, which is a property no consumer can use and no
//     test can state simply.
//   * Back-pressure from the far end is one gate deep ((`!full || ready`) from
//     `rem_req_ready` to `req_ready`), not a ripple through the pipe.
//
// `MOSAIC_REMOTE_LATENCY` is a real delay in the hardware and not a documented
// intention: the pipelines are `LATENCY` storage words each, and
// `MOSAIC_REMOTE_LINK_MUTANT_ONE_CYCLE` forces them to one stage so the
// testbench can show what a link that "always answers in one cycle" does.
//
// The design assumes a **minimum of one cycle in each direction**, and enforces
// it: `LATENCY` is clamped to at least 1, so a profile that set
// `MOSAIC_REMOTE_LATENCY` to 0 would get a one-cycle hop rather than a
// combinational path from the home cluster into the remote cluster's issue
// queue. A zero-stage pipeline is not a link.
//
// ------------------------------------------------------ no cycle between the channels
//
// The channels are separate, and the only resource they share is the credit
// table. That is enough to couple them transitively: a stalled home response
// port fills the response pipeline, which stops matches, which keeps entries
// live, which eventually refuses requests. The direction of that dependency is
// the point -- it is a chain and not a cycle:
//
//     rsp_ready -> rsp_pipe -> match -> entry free -> req_ready -> req_pipe -> rem_req_ready
//
// Nothing on the right-hand side feeds anything on the left. Progress flows one
// way: a request is only accepted if a credit is free, and a credit is only
// freed by a response (or a kill). Under the standard environment assumption --
// a side that is stalled eventually asserts its `ready`, and a side that has
// something to send eventually asserts its `valid` -- every cycle above
// terminates, so the link cannot deadlock and no request is lost.
//
// The card's fail criterion is the *opposite* arrangement: a request that is
// refused because the response path has a packet parked in it, with no causal
// chain to justify it. That is a shared buffer shared and nothing more, and
// `MOSAIC_REMOTE_LINK_MUTANT_SHARED_CHANNEL` is exactly that defect: it makes
// `req_ready` depend on the response pipeline being empty. The directed
// back-pressure phase asserts the property directly -- with the response path
// saturated and the table not full, a request must still be accepted -- so the
// mutant fails on a check that names the requirement rather than on a timeout.
//
// ------------------------------------------------------------- what is *not* here
//
//   * No functional unit. The link does not know what an opcode means; the
//     payload is opaque to it. The remote unit and its cluster's routing are
//     the consumer's business.
//   * No route field. One link instance serves exactly one home/remote cluster
//     pair, so the route is the instance's wiring and not a packet field. A
//     field the link could not check would be carried, stored and never
//     validated -- and the first thing it would hide is a mis-routed response.
//     I-029's steering decides *which* link a uop goes to; that decision happens
//     above this module.
//   * No epoch or generation of its own. The home side owns the identity,
//     including its generation, and the link compares identities bit for bit.
//   * No re-ordering. Responses are delivered in the order they arrive, which
//     is not necessarily the order the requests were issued; the link never
//     assumes the network is FIFO. That is why delivery is driven by the
//     response port and not by the request order.
//
// ------------------------------------------------------------- an assumption it makes
//
// The identity on the wire must be unique among the requests the home side has
// in flight *and* among the requests it has killed but whose response may still
// arrive. If the home re-issued a killed uop with the same identity, the old
// response would be indistinguishable from the new one -- not because the check
// is weak, but because the two packets would be carrying identical names. The
// generation in the identity is what the home side owns to prevent that; a
// re-issue must bump it. `remote.kill_with_delayed_response` tests the case as
// the card states it, with a *different* identity for the new request.
//
// ------------------------------------------------------------------ mutants
//
// `-DMOSAIC_REMOTE_LINK_MUTANT_*` injects one defect each; none is defined in
// the shipping build. The table with real output is in
// results/reports/I-028-remote-link.md.
// ============================================================================

`default_nettype none
`resetall

/* verilator lint_off UNUSEDPARAM */
// The generated header declares one localparam per configuration knob for the
// whole project; this module names two of them and the rest belong to other
// modules. `mosaic_uop_pkg` carries the frozen identity, operand and completion
// widths and includes the generated packages itself, so this file needs no
// second include of its own -- and `mosaic_id_pkg.svh` is generated without an
// include guard, so a second include in one compilation unit would be a
// duplicate package definition.
`include "mosaic_uop_pkg.sv"
/* verilator lint_on UNUSEDPARAM */

// The mutant switches live at compilation-unit scope because `PIPE_DEPTH` is a
// port-width input to the module and a parameter cannot read a `define that is
// written inside the module body. The names are prefixed so that they cannot
// collide with another file's unit-scope declaration.
`ifdef MOSAIC_REMOTE_LINK_MUTANT_STALE_ACCEPT
  localparam bit MOSAIC_LINK_MUT_STALE_ACCEPT = 1'b1;   // accept without a live entry
`else
  localparam bit MOSAIC_LINK_MUT_STALE_ACCEPT = 1'b0;
`endif

`ifdef MOSAIC_REMOTE_LINK_MUTANT_MATCH_ID_ONLY
  localparam bit MOSAIC_LINK_MUT_MATCH_ID_ONLY = 1'b1;  // pair on the link id alone
`else
  localparam bit MOSAIC_LINK_MUT_MATCH_ID_ONLY = 1'b0;
`endif

`ifdef MOSAIC_REMOTE_LINK_MUTANT_ONE_CYCLE
  localparam bit MOSAIC_LINK_MUT_ONE_CYCLE = 1'b1;      // ignore the latency
`else
  localparam bit MOSAIC_LINK_MUT_ONE_CYCLE = 1'b0;
`endif

`ifdef MOSAIC_REMOTE_LINK_MUTANT_NO_CREDIT_ON_KILL
  localparam bit MOSAIC_LINK_MUT_NO_CREDIT_KILL = 1'b1; // free the entry, keep the credit
`else
  localparam bit MOSAIC_LINK_MUT_NO_CREDIT_KILL = 1'b0;
`endif

`ifdef MOSAIC_REMOTE_LINK_MUTANT_SHARED_CHANNEL
  localparam bit MOSAIC_LINK_MUT_SHARED_CHANNEL = 1'b1; // response storage gates requests
`else
  localparam bit MOSAIC_LINK_MUT_SHARED_CHANNEL = 1'b0;
`endif

`ifdef MOSAIC_REMOTE_LINK_MUTANT_ID_DROPPED
  localparam bit MOSAIC_LINK_MUT_ID_DROPPED = 1'b1;     // identity does not survive
`else
  localparam bit MOSAIC_LINK_MUT_ID_DROPPED = 1'b0;
`endif

module mosaic_remote_link #(
    // -------------------------------------------------------------- geometry
    // `localparam` and not `parameter`: a caller can pick a different profile
    // by regenerating the packages, and can never override one of these into a
    // second geometry that disagrees with the generated ones.
    localparam int unsigned ENTRIES = mosaic_cfg_pkg::MOSAIC_IQ_ENTRIES,

    // A link is at least one registered hop in each direction. A profile that
    // asked for zero would get a wire, which is not a link, so the value is
    // clamped rather than used as given -- and the clamp is visible here.
    localparam int unsigned LATENCY = (mosaic_cfg_pkg::MOSAIC_REMOTE_LATENCY < 1)
                                      ? 1 : mosaic_cfg_pkg::MOSAIC_REMOTE_LATENCY,

    // The pipeline depth actually built. The mutant switch above forces one
    // stage so a case can show what "the latency parameter was ignored" does.
    localparam int unsigned PIPE_DEPTH = MOSAIC_LINK_MUT_ONE_CYCLE ? 1 : LATENCY,

    // ------------------------------------------------- identity and payload
    // The identity is `mosaic_id_pkg::macro_id_t` -- `{hart, rob_index,
    // rob_gen, uop_index}` -- and its width is the sum of the generated field
    // widths rather than a second copy of the struct. `mosaic_uop_pkg` is the
    // frozen definition of that struct and of the operand widths; this module
    // reuses them so a change there cannot leave the link carrying a packet the
    // rest of the core no longer sends.
    localparam int unsigned ID_W  = mosaic_uop_pkg::HART_W + mosaic_uop_pkg::ROB_INDEX_W
                                  + mosaic_uop_pkg::ROB_GEN_W + mosaic_uop_pkg::UOP_INDEX_W,

    // The destination's `{tag, gen}`. `x0` is not carried: a uop with no
    // architectural destination produces no value, so it is not sent to a
    // remote unit at all, and the writeback path applies the x0 rule where that
    // rule belongs.
    localparam int unsigned DST_W = mosaic_uop_pkg::TAG_W + mosaic_uop_pkg::GEN_W,

    // `mosaic_pkg::alu_op_e` has sixteen encodings, which is exactly four bits.
    localparam int unsigned OP_W   = 4,
    localparam int unsigned WORD_W = mosaic_uop_pkg::XLEN,

    localparam int unsigned LINK_ID_W = (ENTRIES <= 1) ? 1 : $clog2(ENTRIES),
    localparam int unsigned OCC_W     = $clog2(ENTRIES + 1),

    // ---------------------------------------------- request payload layout
    // Low bits first: identity, destination, opcode, immediate, source 1,
    // source 2. The link id sits above all of it and is written by the link
    // itself, which is why the home port does not have the bits at all: a field
    // the home side drove and the link overwrote would be a wire with no
    // reader, and the first thing it would hide is a link that passed the
    // remote side's name through instead of allocating one.
    localparam int unsigned REQ_ID_LO  = 0,
    localparam int unsigned REQ_DST_LO = REQ_ID_LO + ID_W,
    localparam int unsigned REQ_OP_LO  = REQ_DST_LO + DST_W,
    localparam int unsigned REQ_IMM_LO = REQ_OP_LO + OP_W,
    localparam int unsigned REQ_S1_LO  = REQ_IMM_LO + WORD_W,
    localparam int unsigned REQ_S2_LO  = REQ_S1_LO + WORD_W,
    localparam int unsigned REQ_LID_LO = REQ_S2_LO + WORD_W,

    // What the home side hands over, and what travels between the clusters.
    localparam int unsigned REQ_BODY_W = REQ_LID_LO,
    localparam int unsigned REQ_W      = REQ_LID_LO + LINK_ID_W,

    // ------------------------------------------------- response payload layout
    localparam int unsigned RSP_ID_LO  = 0,
    localparam int unsigned RSP_DST_LO = RSP_ID_LO + ID_W,
    localparam int unsigned RSP_VAL_LO = RSP_DST_LO + DST_W,
    localparam int unsigned RSP_FLT_LO = RSP_VAL_LO + WORD_W,
    localparam int unsigned RSP_LID_LO = RSP_FLT_LO + 1,
    localparam int unsigned RSP_W      = RSP_LID_LO + LINK_ID_W,

    // A counter of events, not of geometry: the same 32-bit total counter every
    // other module in this core exposes (mosaic_rob's o_alloc_total and
    // o_retired_total). One event per cycle at most, and the runner's largest
    // budget is 200000 cycles, so no counter here can come close to wrapping.
    localparam int unsigned CNT_W = 32
) (
    input  logic                        clk,
    input  logic                        rst,

    // ------------------------------------------------- home request port
    // A request is accepted on exactly those edges where `req_valid` and
    // `req_ready` are both high; the payload must be stable while it waits. It
    // carries everything the remote unit needs -- identity, destination,
    // opcode, immediate and both operands -- so the far side never looks
    // anything up in the home cluster's state.
    input  logic                        req_valid,
    output logic                        req_ready,
    input  logic [REQ_BODY_W-1:0]       req_payload,

    // ----------------------------------------------- remote request port
    // Registered in both directions of the handshake: `rem_req_valid` and
    // `rem_req_payload` are functions of the pipeline registers only.
    output logic                        rem_req_valid,
    input  logic                        rem_req_ready,
    output logic [REQ_W-1:0]            rem_req_payload,

    // ---------------------------------------------- remote response port
    // `rem_rsp_ready` is high whenever the response pipeline can take an item.
    // A response that is transferred but matches no live entry is consumed and
    // dropped in the same cycle -- `ready` means "accepted", and a real link
    // cannot hold a packet it has no use for. Dropping it without consuming it
    // would stall the remote end forever.
    input  logic                        rem_rsp_valid,
    output logic                        rem_rsp_ready,
    input  logic [RSP_W-1:0]            rem_rsp_payload,

    // --------------------------------------------------- home response port
    output logic                        rsp_valid,
    input  logic                        rsp_ready,
    output logic [RSP_W-1:0]            rsp_payload,

    // -------------------------------------------------------- kill and flush
    // `kill_valid` kills the one outstanding request whose identity is
    // `kill_ident`; `flush_valid` kills every outstanding request. A kill that
    // matches nothing is counted rather than ignored, because "the request I
    // killed was not in flight" is a fact the home side needs to be able to
    // see.
    input  logic                        kill_valid,
    input  logic [ID_W-1:0]             kill_ident,
    input  logic                        flush_valid,

    // ------------------------------------------------------ credit accounts
    output logic [CNT_W-1:0]            o_issued_ctr,     // credits taken
    output logic [CNT_W-1:0]            o_returned_ctr,   // credits given back
    output logic [CNT_W-1:0]            o_matched_ctr,    // returned by a response
    output logic [CNT_W-1:0]            o_killed_ctr,     // returned by kill/flush
    output logic [CNT_W-1:0]            o_outstanding,    // entries live now
    output logic [CNT_W-1:0]            o_stale_rsp_ctr,  // responses dropped
    output logic [CNT_W-1:0]            o_alias_rsp_ctr,  // dropped, live slot, wrong identity
    output logic [CNT_W-1:0]            o_delivered_ctr,  // responses handed to home
    output logic [CNT_W-1:0]            o_kill_missed_ctr,// kills that matched nothing
    output logic [CNT_W-1:0]            o_flush_ctr,      // flush events taken
    output logic [CNT_W-1:0]            o_req_stall_ctr,  // request offered, no room
    output logic [CNT_W-1:0]            o_rsp_stall_ctr,  // response offered, no room

    // ------------------------------------------------------- whole state
    // Every register the module owns, as driver wires, so a testbench can
    // compare the *whole* unit state every cycle. Fields that belong to an
    // invalid entry or an empty pipeline stage are reported as zero rather than
    // as whatever the unreset storage holds, so the observation is a function
    // of the state that has meaning and never of power-up contents.
    output logic [ENTRIES-1:0]          o_entry_valid,
    output logic [ENTRIES*ID_W-1:0]     o_entry_id,
    output logic [ENTRIES*DST_W-1:0]    o_entry_dst,
    output logic [PIPE_DEPTH-1:0]       o_req_pipe_valid,
    output logic [PIPE_DEPTH*REQ_W-1:0] o_req_pipe,
    output logic [PIPE_DEPTH-1:0]       o_rsp_pipe_valid,
    output logic [PIPE_DEPTH*RSP_W-1:0] o_rsp_pipe,

    // ----------------------------------------------- elaborated geometry
    // Read back out of the instance so the testbench wrapper and the C++ driver
    // size themselves from the hardware rather than from a second copy of the
    // arithmetic. A mismatch there would show up as a slice the driver never
    // looks at -- a test that got weaker without failing.
    output logic [31:0]                 o_entries,
    output logic [31:0]                 o_latency,
    output logic [31:0]                 o_pipe_depth,
    output logic [31:0]                 o_id_w,
    output logic [31:0]                 o_dst_w,
    output logic [31:0]                 o_op_w,
    output logic [31:0]                 o_word_w,
    output logic [31:0]                 o_link_id_w,
    output logic [31:0]                 o_req_body_w,
    output logic [31:0]                 o_req_w,
    output logic [31:0]                 o_rsp_w,
    output logic [31:0]                 o_cnt_w,
    output logic [31:0]                 o_req_id_lo,
    output logic [31:0]                 o_req_dst_lo,
    output logic [31:0]                 o_req_op_lo,
    output logic [31:0]                 o_req_imm_lo,
    output logic [31:0]                 o_req_s1_lo,
    output logic [31:0]                 o_req_s2_lo,
    output logic [31:0]                 o_req_lid_lo,
    output logic [31:0]                 o_rsp_id_lo,
    output logic [31:0]                 o_rsp_dst_lo,
    output logic [31:0]                 o_rsp_val_lo,
    output logic [31:0]                 o_rsp_flt_lo,
    output logic [31:0]                 o_rsp_lid_lo
);

  // ---------------------------------------------------------------- guards
  // Geometry rules as elaboration errors rather than as comments. A profile
  // that violated one would not elaborate, which is the only kind of check that
  // cannot be forgotten by a later reader.

  // The link id has to name every entry exactly once. `$clog2` gives an entry
  // count that may not fill the index space, and an index space with holes is
  // fine (every slot is still addressable) -- but an index space *smaller* than
  // the table would leave entries that no response could ever name, i.e. a
  // credit that can never be returned. That is refused rather than rounded, the
  // same way mosaic_predictor refuses to wrap a truncating index onto a valid
  // one.
  localparam bit LID_TOO_NARROW = ((1 << LINK_ID_W) < ENTRIES);

  // A table of zero entries has no credit to take, so no request could ever be
  // accepted and the module would be a black hole rather than a link.
  localparam bit NO_ENTRIES = (ENTRIES < 1);

  generate
    if (LID_TOO_NARROW) begin : g_bad_lid_width
      mosaic_remote_link_contract_violation u_lid_width();
    end
    if (NO_ENTRIES) begin : g_bad_entries
      mosaic_remote_link_contract_violation u_entries();
    end
  endgenerate

  // ------------------------------------------------------------ the table
  // Validity is a separate reset bit per entry, exactly as mosaic_rename does
  // for its tags and mosaic_ram's header requires: reset cost is control state,
  // not ENTRIES x WIDTH of storage. The identity and destination arrays are not
  // reset and are read only where `entry_valid` holds.
  //
  // Allocation is **lowest free index**, with no rotation. A round-robin
  // pointer would spread allocations over the table and make a recycled slot a
  // rare event; the hazard this module exists to close -- a late response
  // naming a slot that has since been handed to another request -- is exactly
  // the *common* case when a freed slot is the first one taken again. The
  // design takes the adversarial policy on purpose: what the test exercises
  // every kill is what a rotation would exercise once in ENTRIES kills.
  logic                entry_valid [0:ENTRIES-1];
  logic [ID_W-1:0]     entry_id    [0:ENTRIES-1];
  logic [DST_W-1:0]    entry_dst   [0:ENTRIES-1];

  // --------------------------------------------------------- the two hops
  // Stage 0 is the end nearest the port that receives; the highest stage is the
  // end nearest the port that emits. An item therefore walks the pipe once, and
  // its position is what makes the delay a delay.
  logic              req_pipe_valid [0:PIPE_DEPTH-1];
  logic [REQ_W-1:0]  req_pipe_data  [0:PIPE_DEPTH-1];
  logic              rsp_pipe_valid [0:PIPE_DEPTH-1];
  logic [RSP_W-1:0]  rsp_pipe_data  [0:PIPE_DEPTH-1];

  // ----------------------------------------------------------- combinational
  logic                    alloc_free;
  logic [LINK_ID_W-1:0]    alloc_slot;
  logic                    kill_win   [0:ENTRIES-1];
  logic                    flush_win  [0:ENTRIES-1];
  logic                    rsp_win    [0:ENTRIES-1];
  logic                    kill_hit;
  logic [LINK_ID_W-1:0]    kill_slot;
  logic                    rsp_xfer;
  logic [LINK_ID_W-1:0]    rsp_lid;
  logic [LINK_ID_W-1:0]    rsp_lid_s;   // range-checked index into the table
  logic [ID_W-1:0]         rsp_id;
  logic [DST_W-1:0]        rsp_dst;
  logic [OCC_W-1:0]        entry_count;
  logic [OCC_W-1:0]        freed_count;
  logic                    resp_matched;
  logic                    rsp_pipe_busy;
  logic                    req_shift;
  logic                    req_accept;
  logic                    rsp_shift;
  logic [REQ_W-1:0]        req_item;
  logic [RSP_W-1:0]        rsp_item;

  assign req_shift = !req_pipe_valid[PIPE_DEPTH-1] || rem_req_ready;
  assign rsp_shift = !rsp_pipe_valid[PIPE_DEPTH-1] || rsp_ready;

  assign rem_req_valid   = req_pipe_valid[PIPE_DEPTH-1];
  assign rem_req_payload = req_pipe_data[PIPE_DEPTH-1];
  assign rsp_valid       = rsp_pipe_valid[PIPE_DEPTH-1];
  assign rsp_payload     = rsp_pipe_data[PIPE_DEPTH-1];

  // The far side may only take what the pipe can hand over, and the home side
  // may only hand over what the pipe can take -- and only if a credit is free.
  // Neither ready signal depends on the corresponding `valid`, which is the
  // rule that keeps a valid/ready pair from becoming a combinational loop with
  // the module on the other side.
  assign rem_rsp_ready = rsp_shift;
  assign req_ready     = alloc_free && req_shift
                         && !(MOSAIC_LINK_MUT_SHARED_CHANNEL && rsp_pipe_busy);

  assign req_accept = req_valid && req_ready;
  assign rsp_xfer   = rem_rsp_valid && rem_rsp_ready;

  // A reduction operator does not apply to an unpacked array, and that is a
  // language rule rather than a tool's opinion (slang and Verilator agree on
  // it). The two "is anything in there" questions this module asks are spelled
  // out as loops instead.
  always_comb begin
    int unsigned s;
    rsp_pipe_busy = 1'b0;
    for (s = 0; s < PIPE_DEPTH; s = s + 1) begin
      if (rsp_pipe_valid[s]) rsp_pipe_busy = 1'b1;
    end
  end

  // ---------------------------------------------------------- allocation
  // The lowest invalid entry. The scan reads the table as it stands before this
  // cycle's edge, so an entry freed in this cycle is *not* offered here: the
  // request waits one cycle. That is one cycle of extra back-pressure bought in
  // exchange for an allocation never racing the release that makes the slot
  // available.
  always_comb begin
    int unsigned idx;
    alloc_free = 1'b0;
    alloc_slot = {LINK_ID_W{1'b0}};
    for (idx = 0; idx < ENTRIES; idx = idx + 1) begin
      if (!alloc_free && !entry_valid[idx]) begin
        alloc_free = 1'b1;
        alloc_slot = LINK_ID_W'(idx);
      end
    end
  end

  // --------------------------------------------------------------- kill
  // Lowest-index match, so the choice does not depend on the storage order of
  // an array. A kill of an identity that is not in flight is a miss and is
  // counted.
  always_comb begin
    int unsigned idx;
    kill_hit  = 1'b0;
    kill_slot = {LINK_ID_W{1'b0}};
    for (idx = 0; idx < ENTRIES; idx = idx + 1) begin
      if (!kill_hit && entry_valid[idx] && (entry_id[idx] == kill_ident)) begin
        kill_hit  = 1'b1;
        kill_slot = LINK_ID_W'(idx);
      end
    end
  end

  // ------------------------------------------------------- pairing and release
  assign rsp_lid = rem_rsp_payload[RSP_LID_LO +: LINK_ID_W];
  assign rsp_id  = rem_rsp_payload[RSP_ID_LO  +: ID_W];
  assign rsp_dst = rem_rsp_payload[RSP_DST_LO +: DST_W];

  // `$clog2` can name indices past a smaller table, so a link id that does not
  // fill its field is range-checked before it reaches an array. For the
  // shipping geometry (8 entries in a 3-bit field) the check is a tautology and
  // is not elaborated at all: emitting a comparison Verilator can prove
  // constant is exactly the dead logic -Wall exists to report.
  localparam bit LID_EXACT = (ENTRIES == (1 << LINK_ID_W));

  generate
    if (LID_EXACT) begin : g_lid_exact
      assign rsp_lid_s = rsp_lid;
    end else begin : g_lid_may_exceed
      always_comb begin
        rsp_lid_s = (rsp_lid < LINK_ID_W'(ENTRIES)) ? rsp_lid : {LINK_ID_W{1'b0}};
      end
    end
  endgenerate

  always_comb begin
    int unsigned idx;
    freed_count  = {OCC_W{1'b0}};
    resp_matched = 1'b0;
    for (idx = 0; idx < ENTRIES; idx = idx + 1) begin
      // A flush takes every live entry; a kill takes the one it named, unless a
      // flush is taking them all anyway.
      flush_win[idx] = flush_valid && entry_valid[idx];
      kill_win[idx]  = kill_valid && !flush_valid && kill_hit
                       && (kill_slot == LINK_ID_W'(idx));

      // The response is accepted only when the link id names a live entry that
      // holds *this* identity and destination. Both halves are needed: the
      // index alone aliases when a slot is recycled, and the identity alone
      // would need a search. This is the check the card's fail criterion is
      // about -- a late response must not be delivered into a recycled slot --
      // and it is decided here, from the link's own state, not at a consumer.
      rsp_win[idx] = rsp_xfer && !flush_win[idx] && !kill_win[idx]
                     && (rsp_lid == LINK_ID_W'(idx))
                     && (MOSAIC_LINK_MUT_STALE_ACCEPT
                         || (entry_valid[idx]
                             && (MOSAIC_LINK_MUT_MATCH_ID_ONLY
                                 || ((entry_id[idx] == rsp_id)
                                     && (entry_dst[idx] == rsp_dst)))));

      if (flush_win[idx] || kill_win[idx] || rsp_win[idx]) begin
        freed_count = freed_count + OCC_W'(1);
      end
      if (rsp_win[idx]) resp_matched = 1'b1;
    end
  end

  // Recomputing the population rather than reading `o_outstanding`: the test
  // checks the two against each other, and a counter derived from the same
  // expression it is checked against would agree with itself.
  always_comb begin
    int unsigned idx;
    entry_count = {OCC_W{1'b0}};
    for (idx = 0; idx < ENTRIES; idx = idx + 1) begin
      if (entry_valid[idx]) entry_count = entry_count + OCC_W'(1);
    end
  end

  // ---------------------------------------------------- the request payload
  // The allocated slot is what names the request for the rest of its life, and
  // it is written above everything the home side supplied, so the remote side
  // always receives the name the table knows the request by.
  assign req_item = {alloc_slot, req_payload};

  // --------------------------------------------------- the response payload
  always_comb begin
    rsp_item = rem_rsp_payload;
    if (MOSAIC_LINK_MUT_ID_DROPPED) begin
      rsp_item[RSP_ID_LO +: ID_W] = {ID_W{1'b0}};
    end
  end

  // ------------------------------------------------------------ sequential
  always_ff @(posedge clk) begin
    if (rst) begin
      for (int unsigned k = 0; k < ENTRIES; k = k + 1) begin
        entry_valid[k] <= 1'b0;
      end
      for (int unsigned s = 0; s < PIPE_DEPTH; s = s + 1) begin
        req_pipe_valid[s] <= 1'b0;
        rsp_pipe_valid[s] <= 1'b0;
      end
    end else begin
      // ---- the table: release, then allocate. The two cannot touch the same
      // entry in one cycle, because the allocation scan only ever returns an
      // entry that is invalid *before* this edge while every release leaves an
      // entry that is valid before it. The comment is the argument; a priority
      // here would hide the day it stopped being true.
      for (int unsigned k = 0; k < ENTRIES; k = k + 1) begin
        if (flush_win[k] || kill_win[k] || rsp_win[k]) begin
          entry_valid[k] <= 1'b0;
        end
      end

      if (req_accept) begin
        entry_valid[alloc_slot] <= 1'b1;
        entry_id[alloc_slot]    <= req_payload[REQ_ID_LO  +: ID_W];
        entry_dst[alloc_slot]   <= req_payload[REQ_DST_LO +: DST_W];
      end

      // ---- the request hop. The whole pipe moves together or not at all: the
      // last stage is emptied by the far side accepting, and everything behind
      // it follows in the same edge.
      if (req_shift) begin
        for (int unsigned s = PIPE_DEPTH-1; s > 0; s = s - 1) begin
          req_pipe_valid[s] <= req_pipe_valid[s-1];
          req_pipe_data[s]  <= req_pipe_data[s-1];
        end
        req_pipe_valid[0] <= req_accept;
        req_pipe_data[0]  <= req_item;
      end

      // ---- the response hop. Loaded only by a matched response: a transferred
      // response that matched nothing is consumed and dropped, so a stale
      // packet can never enter the pipe and be delivered later.
      if (rsp_shift) begin
        for (int unsigned s = PIPE_DEPTH-1; s > 0; s = s - 1) begin
          rsp_pipe_valid[s] <= rsp_pipe_valid[s-1];
          rsp_pipe_data[s]  <= rsp_pipe_data[s-1];
        end
        rsp_pipe_valid[0] <= resp_matched;
        rsp_pipe_data[0]  <= rsp_item;
      end
    end
  end

  // ------------------------------------------------------------- counters
  // Each counter is driven by the same event that moves the state above, so the
  // conservation law cannot drift from the table it describes.
  always_ff @(posedge clk) begin
    if (rst) begin
      o_issued_ctr     <= {CNT_W{1'b0}};
      o_returned_ctr   <= {CNT_W{1'b0}};
      o_matched_ctr    <= {CNT_W{1'b0}};
      o_killed_ctr     <= {CNT_W{1'b0}};
      o_outstanding    <= {CNT_W{1'b0}};
      o_stale_rsp_ctr  <= {CNT_W{1'b0}};
      o_alias_rsp_ctr  <= {CNT_W{1'b0}};
      o_delivered_ctr  <= {CNT_W{1'b0}};
      o_kill_missed_ctr<= {CNT_W{1'b0}};
      o_flush_ctr      <= {CNT_W{1'b0}};
      o_req_stall_ctr  <= {CNT_W{1'b0}};
      o_rsp_stall_ctr  <= {CNT_W{1'b0}};
    end else begin
      if (req_accept)     o_issued_ctr  <= o_issued_ctr + CNT_W'(1);
      if (resp_matched)   o_matched_ctr <= o_matched_ctr + CNT_W'(1);
      if (MOSAIC_LINK_MUT_NO_CREDIT_KILL) begin
        // Mutation: the entry is freed (above) but the credit is not accounted
        // as returned, so the table and the accounts disagree by one per kill.
        o_returned_ctr <= o_returned_ctr + CNT_W'(resp_matched ? 1 : 0);
        o_killed_ctr   <= o_killed_ctr;
      end else begin
        // `freed_count` counts every entry released this cycle, and a matched
        // response is one of those releases -- so the credits returned are
        // `freed_count` in total and `freed_count - matched` of them came from
        // a kill or a flush. Written this way the two counters cannot disagree
        // with the table they describe.
        o_returned_ctr <= o_returned_ctr + CNT_W'(freed_count);
        o_killed_ctr   <= o_killed_ctr + CNT_W'(freed_count)
                                        - CNT_W'(resp_matched ? 1 : 0);
      end
      o_outstanding    <= o_outstanding + CNT_W'(req_accept ? 1 : 0)
                                        - CNT_W'(freed_count);
      if (rsp_xfer && !resp_matched) o_stale_rsp_ctr <= o_stale_rsp_ctr + CNT_W'(1);
      if (rsp_xfer && !resp_matched && entry_valid[rsp_lid_s]
          && !kill_win[rsp_lid_s] && !flush_win[rsp_lid_s]) begin
        o_alias_rsp_ctr <= o_alias_rsp_ctr + CNT_W'(1);
      end
      if (rsp_valid && rsp_ready) o_delivered_ctr <= o_delivered_ctr + CNT_W'(1);
      if (kill_valid && !flush_valid && !kill_hit) begin
        o_kill_missed_ctr <= o_kill_missed_ctr + CNT_W'(1);
      end
      if (flush_valid && (entry_count != {OCC_W{1'b0}})) begin
        o_flush_ctr <= o_flush_ctr + CNT_W'(1);
      end
      if (req_valid && !req_ready) o_req_stall_ctr <= o_req_stall_ctr + CNT_W'(1);
      if (rem_rsp_valid && !rem_rsp_ready) begin
        o_rsp_stall_ctr <= o_rsp_stall_ctr + CNT_W'(1);
      end
    end
  end

  // -------------------------------------------------------- observation
  always_comb begin
    int unsigned k;
    o_entry_valid = {ENTRIES{1'b0}};
    for (k = 0; k < ENTRIES; k = k + 1) begin
      o_entry_valid[k] = entry_valid[k];
      // Zero where the entry is invalid: the identity array is not reset, and a
      // stale word there means nothing. What the test compares is the pair
      // (valid, identity-if-valid), which is the whole contract.
      o_entry_id[k*ID_W +: ID_W] = entry_valid[k] ? entry_id[k] : {ID_W{1'b0}};
      o_entry_dst[k*DST_W +: DST_W] = entry_valid[k] ? entry_dst[k] : {DST_W{1'b0}};
    end
  end

  always_comb begin
    int unsigned s;
    o_req_pipe_valid = {PIPE_DEPTH{1'b0}};
    o_rsp_pipe_valid = {PIPE_DEPTH{1'b0}};
    o_req_pipe       = {(PIPE_DEPTH*REQ_W){1'b0}};
    o_rsp_pipe       = {(PIPE_DEPTH*RSP_W){1'b0}};
    for (s = 0; s < PIPE_DEPTH; s = s + 1) begin
      o_req_pipe_valid[s] = req_pipe_valid[s];
      o_rsp_pipe_valid[s] = rsp_pipe_valid[s];
      if (req_pipe_valid[s]) o_req_pipe[s*REQ_W +: REQ_W] = req_pipe_data[s];
      if (rsp_pipe_valid[s]) o_rsp_pipe[s*RSP_W +: RSP_W] = rsp_pipe_data[s];
    end
  end

  assign o_entries   = 32'(ENTRIES);
  assign o_latency   = 32'(LATENCY);
  assign o_pipe_depth= 32'(PIPE_DEPTH);
  assign o_id_w      = 32'(ID_W);
  assign o_dst_w     = 32'(DST_W);
  assign o_op_w      = 32'(OP_W);
  assign o_word_w    = 32'(WORD_W);
  assign o_link_id_w = 32'(LINK_ID_W);
  assign o_req_body_w= 32'(REQ_BODY_W);
  assign o_req_w     = 32'(REQ_W);
  assign o_rsp_w     = 32'(RSP_W);
  assign o_cnt_w     = 32'(CNT_W);
  assign o_req_id_lo = 32'(REQ_ID_LO);
  assign o_req_dst_lo= 32'(REQ_DST_LO);
  assign o_req_op_lo = 32'(REQ_OP_LO);
  assign o_req_imm_lo= 32'(REQ_IMM_LO);
  assign o_req_s1_lo = 32'(REQ_S1_LO);
  assign o_req_s2_lo = 32'(REQ_S2_LO);
  assign o_req_lid_lo= 32'(REQ_LID_LO);
  assign o_rsp_id_lo = 32'(RSP_ID_LO);
  assign o_rsp_dst_lo= 32'(RSP_DST_LO);
  assign o_rsp_val_lo= 32'(RSP_VAL_LO);
  assign o_rsp_flt_lo= 32'(RSP_FLT_LO);
  assign o_rsp_lid_lo= 32'(RSP_LID_LO);

endmodule

`default_nettype wire
