// ============================================================================
// tb_core_act.cpp -- CASE=core.act_dut, work package V-043.
//
// Run one ACT4 (riscv-arch-test) self-checking ELF on the integrated
// out-of-order core and report the ELF's own verdict.
//
// ---------------------------------------------------------------- why this case
//
// The V-043 card requires the machine to execute the applicable ACT4
// architectural tests itself: an ELF that the reference model accepted proves
// nothing about the core unless the core runs it. The ELFs are generated by the
// frozen ACT4 checkout (UDB + Sail 0.14.1), compiled by the frozen toolchain and
// carry their expected signature from Sail (the `RVTEST_SELFCHECK` signature
// file) inside their own `.data`. Each `RVTEST_SIGUPD` compares the value the
// core computed with that preloaded word and jumps to a failure handler on a
// mismatch; `RVMODEL_HALT_PASS` (`sw x1,0(tohost)` with x1 = 1) ends a passing
// run and `RVMODEL_HALT_FAIL` (x1 = 3) a failing one. The DUT is therefore never
// its own oracle: the expectation was computed by Sail and is executed, not
// re-derived, by the core.
//
// ------------------------------------------------------------- the exit protocol
//
// The core is run until it *retires* a store to the ELF's `tohost` symbol with a
// non-zero value, which is the ACT4 exit protocol. The value decides the
// verdict: bit 0 set is PASS, anything else (including the value 3 the failure
// handler writes) is FAIL. The store is observed on the retirement port, so a
// store that is on the wrong path and squashed does not end the run -- only a
// committed one does.
//
// The `tohost` address is read from the loaded image's symbol table, never
// assumed: ACT4 links `tohost` into `.tohost` at an address the linker chooses,
// and it is not the profile's own `MOSAIC_TOHOST` (which is inside the ELF's
// text for these images). Watching the symbol is what makes the protocol exact.
//
// ------------------------------------------------------------ what it checks
//
//   1. the image loads (a non-kOk status is a named refusal, never a partial
//      load);
//   2. the image has the symbols the protocol needs (`tohost`, and an entry
//      point equal to the profile's reset vector);
//   3. the run reaches the ELF's `tohost` store before the cycle bound, and does
//      not stop first (an instruction the core refuses is reported with its PC);
//   4. the value written has bit 0 set (PASS) -- the ELF's own verdict;
//   5. at least one instruction retired, so a run that ended without executing
//      cannot pass vacuously.
//
// --------------------------------------------------------------- controls
//
// The controls are defect injections the case must catch; they are not part of
// the registered run and are described in results/reports/V-043-act4.md:
//
//   * an RTL mutant (`-D MOSAIC_ALU_MUTANT_4`, slt via the unsigned compare)
//     makes the I suite's `slt` cases fail inside the ELF, so the case exits 1;
//   * a corrupted expected-signature word in the ELF's own `.data` makes the
//     in-ELF comparison fail, so the case exits 1.
// ============================================================================

#include <verilated.h>

#include <cctype>
#include <cstdint>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <deque>
#include <fstream>
#include <map>
#include <set>
#include <sstream>
#include <string>
#include <vector>

#include "Vmosaic_core_tb.h"

#include "elf_loader.h"
#include "mem_ref.h"
#include "memory_model.h"
#include "mosaic_platform.h"
#include "sim_common.h"

using mosaic_ref::DataMem;

namespace {

// The reset length every other core case uses, so "release" means the same
// thing here.
constexpr int kResetCycles = 4;
// After the exit store retires, a few cycles so the counters describing the last
// instruction land before they are read.
constexpr int kSettleCycles = 8;
// No commit and no allocation for this long is a hang with a location, not a
// timeout. ACT4 bodies are straight-line blocks with visible progress.
constexpr uint64_t kStallCycles = 200000;
// A bound on the delivered-instruction stream kept for the stop diagnosis.
constexpr size_t kMaxDeliveries = 400000;

struct Failure {
  std::string what;
};

[[noreturn]] void Fail(const std::string& where, const std::string& detail) {
  throw Failure{where + ": " + detail};
}

std::string U64(uint64_t value) { return mosaic::Hex(value); }
std::string Dec(uint64_t value) { return std::to_string(value); }

// ============================================================================
// The loaded program image
// ============================================================================
// Holds the parsed ELF so the run can read its entry point, its `tohost` symbol
// and its loadable segments. The segments are copied into the shared memory
// model (which the fetch and data ports both read), so this class is not a second
// memory -- it is the image the one memory is loaded from.
class ProgImage {
 public:
  bool Load(const std::string& path, std::string* detail) {
    mosaic::Image image;
    const mosaic::LoadStatus status = mosaic::LoadElf(path, &image, detail);
    if (status != mosaic::LoadStatus::kOk) {
      *detail = std::string("ELF refused: ") + mosaic::LoadStatusName(status) + ": " +
                *detail;
      return false;
    }
    elf_ = image;
    entry_ = image.entry;
    for (const mosaic::Segment& seg : image.segments) {
      for (uint64_t i = 0; i < seg.filesz; ++i) {
        bytes_[seg.vaddr + i] = seg.data[i];
      }
    }
    return !bytes_.empty();
  }

  uint64_t entry() const { return entry_; }
  const mosaic::Image& elf() const { return elf_; }
  const std::map<uint64_t, uint8_t>& bytes() const { return bytes_; }

  const mosaic::Symbol* FindSymbol(const std::string& name) const {
    return elf_.FindSymbol(name);
  }

 private:
  mosaic::Image elf_;
  std::map<uint64_t, uint8_t> bytes_;
  uint64_t entry_ = 0;
};

// ============================================================================
// The instruction memory
// ============================================================================
// The fetch port reads one byte image that the data port's stores also update,
// so `fence.i` self-modification is visible to the front end -- a separate,
// static copy of the image would make the store land in one memory and the fetch
// read another, which is not a model of any real machine.
//
// The image is read directly rather than through the shared memory model,
// because the model (correctly) shadows the profile's TOHOST/FROMHOST words with
// the test protocol, and those addresses fall inside these ACT images' `.text`.
// Reading the model would make four code bytes read as the protocol and refuse a
// perfectly legal instruction; the driver keeps the image itself and applies the
// store overlay on top.
//
// A fetch past the image reaches an ECALL with a trap vector installed (the
// convention the other core cases use), so a runaway names itself.
class Imem {
 public:
  struct Request {
    uint64_t addr = 0;
    uint32_t id = 0;
    uint32_t epoch = 0;
  };

  explicit Imem(const std::map<uint64_t, uint8_t>* bytes) : bytes_(bytes) {}

  void Reset() {
    inflight_.clear();
    ready_.clear();
    accepted_ = 0;
  }

  bool HasResponse() const { return !ready_.empty(); }
  const Request& Response() const { return ready_.front(); }
  uint64_t ResponseWord() const { return Word(ready_.front().addr); }
  uint64_t accepted() const { return accepted_; }

  uint32_t Word(uint64_t addr) const {
    uint32_t word = 0;
    bool any = false;
    for (uint64_t b = 0; b < 4; b++) {
      auto it = bytes_->find(addr + b);
      if (it != bytes_->end()) {
        any = true;
        word |= static_cast<uint32_t>(it->second) << (8 * b);
      }
    }
    return any ? word : 0x00000073u;
  }

  void Accept(uint64_t addr, uint32_t id, uint32_t epoch) {
    inflight_.push_back(Entry{Request{addr, id, epoch}, 1});
    accepted_++;
  }

  void PopResponse() { ready_.pop_front(); }

  void Advance() {
    for (size_t i = 0; i < inflight_.size();) {
      if (--inflight_[i].left == 0) {
        ready_.push_back(inflight_[i].req);
        inflight_.erase(inflight_.begin() + static_cast<long>(i));
      } else {
        ++i;
      }
    }
  }

 private:
  struct Entry {
    Request req;
    int left = 0;
  };
  const std::map<uint64_t, uint8_t>* bytes_;
  std::deque<Entry> inflight_;
  std::deque<Request> ready_;
  uint64_t accepted_ = 0;
};

// ============================================================================
// Geometry, read from the elaborated DUT (never re-derived)
// ============================================================================
struct Geometry {
  uint32_t xlen = 0;
  uint32_t retire_width = 0;
  uint64_t reset_vector = 0;
};

Geometry ReadGeometry(Vmosaic_core_tb* dut) {
  Geometry g;
  g.xlen = dut->o_geom_xlen_o;
  g.retire_width = dut->o_geom_retire_width_o;
  g.reset_vector = dut->o_geom_reset_vector_o;
  return g;
}

// Verilator hands a wide port over as a `VlWide` indexed in 32-bit words, two
// per 64-bit lane; narrow ports arrive as plain scalars.
template <typename Wide>
uint64_t PayloadLane(const Wide& wide, uint32_t lane) {
  return static_cast<uint64_t>(wide[lane * 2]) |
         (static_cast<uint64_t>(wide[lane * 2 + 1]) << 32);
}
[[maybe_unused]] inline uint64_t PayloadLane(uint64_t value, uint32_t /*lane*/) {
  return value;
}

// ============================================================================
// The run
// ============================================================================
enum class RunStatus { kPass, kFail, kStopped, kTimeout, kStalled, kSetupError };

const char* StatusName(RunStatus status) {
  switch (status) {
    case RunStatus::kPass: return "PASS";
    case RunStatus::kFail: return "FAIL";
    case RunStatus::kStopped: return "STOP";
    case RunStatus::kTimeout: return "TIMEOUT";
    case RunStatus::kStalled: return "STALL";
    case RunStatus::kSetupError: return "SETUP";
  }
  return "?";
}

struct RunRecord {
  std::string elf;
  uint64_t tohost_addr = 0;
  uint64_t entry = 0;
  uint64_t tohost_value = 0;
  bool tohost_seen = false;
  RunStatus status = RunStatus::kSetupError;
  uint64_t cycles = 0;
  uint64_t retires = 0;
  uint64_t redirects = 0;
  uint64_t traps_taken = 0;
  uint64_t unsupported = 0;
  uint64_t illegal = 0;
  uint64_t stop_pc = 0;
  uint32_t stop_bits = 0;
  uint64_t stop_cycle = 0;
  uint64_t last_trap_cause = 0;
  uint64_t last_trap_pc = 0;
  uint64_t last_trap_tval = 0;
  uint64_t console_chars = 0;
  std::string console_text;
  std::vector<uint64_t> signature;
  bool delivery_tracking_overflowed = false;
  std::string note;
};

class Runner {
 public:
  Runner(Vmosaic_core_tb* dut, const Geometry& g) : dut_(dut), g_(g) {}

  RunRecord Run(const std::string& elf_path, uint64_t max_cycles) {
    RunRecord record;
    record.elf = elf_path;

    ProgImage image;
    std::string load_detail;
    if (!image.Load(elf_path, &load_detail)) {
      record.status = RunStatus::kSetupError;
      record.note = load_detail;
      return record;
    }
    const mosaic::Symbol* tohost = image.FindSymbol("tohost");
    if (tohost == nullptr) {
      record.status = RunStatus::kSetupError;
      record.note = "the image has no `tohost` symbol, so the ACT4 exit protocol "
                    "cannot be observed";
      return record;
    }
    record.tohost_addr = tohost->value;
    record.entry = image.entry();
    tohost_addr_ = tohost->value;

    mosaic::MemoryModel dut_mem;
    {
      std::string detail;
      if (!dut_mem.LoadImage(image.elf(), &detail)) {
        record.status = RunStatus::kSetupError;
        record.note = detail;
        return record;
      }
    }
    // The fetch image: the ELF bytes plus every byte the data port stores, so a
    // `fence.i` self-modifying program is fetched as it wrote it.
    bytes_ = image.bytes();

    Imem imem(&bytes_);
    DataMem dmem(&dut_mem);
    imem.Reset();
    dmem.Reset();
    cycles_ = 0;
    last_commit_ = 0;
    last_alloc_ = 0;
    last_progress_ = 0;
    stop_pc_ = 0;
    stop_bits_ = 0;
    stop_cycle_ = 0;
    delivered_.clear();
    retired_pcs_.clear();
    delivery_tracking_overflowed_ = false;
    last_trap_cause_ = 0;
    last_trap_pc_ = 0;
    last_trap_tval_ = 0;
    pending_low_ = 0;
    console_chars_ = 0;
    console_text_.clear();
    exit_seen_ = false;
    exit_value_ = 0;

    dut_->clk = 0;
    dut_->rst = 1;
    dut_->eval();
    for (int i = 0; i < kResetCycles; i++) Cycle(true, &imem, &dmem);

    // The entry point must be the profile's reset vector: the front end fetches
    // from `o_geom_reset_vector_o` at release, so an image linked elsewhere
    // cannot be run by this core and must be refused rather than half-run.
    if (image.entry() != g_.reset_vector) {
      record.status = RunStatus::kSetupError;
      record.note = "the image entry " + U64(image.entry()) +
                    " is not the profile reset vector " + U64(g_.reset_vector);
      return record;
    }

    while (true) {
      Cycle(false, &imem, &dmem);
      if (exit_seen_) {
        record.tohost_seen = true;
        record.tohost_value = exit_value_;
        break;
      }
      if (dut_->o_stopped_o != 0) {
        record.status = RunStatus::kStopped;
        break;
      }
      if (cycles_ >= max_cycles) {
        record.status = RunStatus::kTimeout;
        break;
      }
      if (cycles_ - last_progress_ > kStallCycles) {
        record.status = RunStatus::kStalled;
        break;
      }
    }
    if (record.status != RunStatus::kStopped && record.status != RunStatus::kTimeout &&
        record.status != RunStatus::kStalled) {
      for (int i = 0; i < kSettleCycles; i++) Cycle(false, &imem, &dmem);
    } else if (record.status == RunStatus::kStopped) {
      for (int i = 0; i < 8 * kSettleCycles; i++) Cycle(false, &imem, &dmem);
    }

    record.cycles = cycles_;
    record.retires = dut_->o_commit_o;
    record.redirects = dut_->o_redirect_o;
    record.traps_taken = dut_->o_csr_trap_o;
    record.unsupported = dut_->o_unsupported_o;
    record.illegal = dut_->o_illegal_o;
    record.stop_pc = stop_pc_;
    record.stop_bits = stop_bits_;
    record.stop_cycle = stop_cycle_;
    record.last_trap_cause = last_trap_cause_;
    record.last_trap_pc = last_trap_pc_;
    record.last_trap_tval = last_trap_tval_;
    record.console_chars = console_chars_;
    record.console_text = console_text_;
    record.delivery_tracking_overflowed = delivery_tracking_overflowed_;

    if (record.status == RunStatus::kStopped && !saw_unsupported_) {
      // Name the refused instruction: the oldest delivery whose PC never retired
      // (the machine quiesces with an empty ROB).
      for (const Delivery& d : delivered_) {
        if (retired_pcs_.find(d.pc) == retired_pcs_.end()) {
          record.stop_pc = d.pc;
          record.stop_bits = d.bits;
          break;
        }
      }
    }
    if (exit_seen_) {
      // ACT4's exit protocol is exact: `RVMODEL_HALT_PASS` writes the value 1
      // and `RVMODEL_HALT_FAIL` writes 3 (rvmodel_macros.h). The value is not
      // HTIF's bit-0 convention, so anything other than 1 is a failure.
      record.status = (exit_value_ == 1ull) ? RunStatus::kPass : RunStatus::kFail;
      if (record.retires == 0) {
        record.status = RunStatus::kFail;
        record.note = "the exit store retired with no instruction counted: the run "
                      "cannot be accepted";
      }
    }

    // Diagnosis only: with MOSAIC_ACT_SIG_DUMP set, read the image's signature
    // region back out of the memory model. Used with the signature-mode ELF
    // (`<name>.sig.elf`, which stores rather than compares) to locate the exact
    // word a self-check disagrees about.
    if (std::getenv("MOSAIC_ACT_SIG_DUMP") != nullptr) {
      const mosaic::Symbol* sig = image.FindSymbol("begin_signature");
      const mosaic::Symbol* sig_end = image.FindSymbol("end_signature");
      if (sig != nullptr && sig_end != nullptr && sig_end->value > sig->value) {
        const uint64_t words = (sig_end->value - sig->value) / 8;
        for (uint64_t i = 0; i < words && i < 65536; ++i) {
          uint64_t value = 0;
          bool ok = true;
          for (uint64_t b = 0; b < 8; ++b) {
            uint64_t byte = 0;
            if (dut_mem.Read(sig->value + i * 8 + b, 1, &byte) !=
                mosaic::AccessStatus::kOk) {
              ok = false;
              break;
            }
            value |= (byte & 0xffull) << (8 * b);
          }
          if (!ok) break;
          record.signature.push_back(value);
        }
      }
    }
    return record;
  }

 private:
  struct Delivery {
    uint64_t pc;
    uint32_t bits;
  };

  void Observe() {
    if (dut_->o_dbg_deliver_valid_o != 0) {
      const uint64_t pc = dut_->o_dbg_deliver_pc_o;
      const uint32_t bits = static_cast<uint32_t>(dut_->o_dbg_deliver_bits_o);
      if (delivered_.empty() || delivered_.back().pc != pc ||
          delivered_.back().bits != bits) {
        if (delivered_.size() < kMaxDeliveries) {
          delivered_.push_back(Delivery{pc, bits});
        } else {
          delivery_tracking_overflowed_ = true;
        }
      }
    }
    const uint32_t mask =
        (g_.retire_width >= 32) ? 0xFFFFFFFFu : ((1u << g_.retire_width) - 1u);
    const uint32_t valid = static_cast<uint32_t>(dut_->ev_valid_o) & mask;
    const uint32_t store = static_cast<uint32_t>(dut_->ev_store_o) & mask;
    const uint32_t trap = static_cast<uint32_t>(dut_->ev_trap_o) & mask;
    for (uint32_t lane = 0; lane < g_.retire_width && lane < 32; lane++) {
      if ((valid & (1u << lane)) == 0) continue;
      retired_pcs_.insert(PayloadLane(dut_->ev_pc_o, lane));
      if ((trap & (1u << lane)) != 0) {
        last_trap_cause_ = PayloadLane(dut_->ev_trap_cause_o, lane);
        last_trap_tval_ = PayloadLane(dut_->ev_trap_tval_o, lane);
        last_trap_pc_ = PayloadLane(dut_->ev_pc_o, lane);
        if (std::getenv("MOSAIC_ACT_DEBUG") != nullptr && debug_traps_ < 40) {
          std::printf("  [trap] #%llu pc=%s cause=%s tval=%s\n",
                      static_cast<unsigned long long>(debug_traps_),
                      U64(last_trap_pc_).c_str(), U64(last_trap_cause_).c_str(),
                      U64(last_trap_tval_).c_str());
          ++debug_traps_;
        }
      }
      if ((store & (1u << lane)) == 0) continue;
      const uint64_t addr = PayloadLane(dut_->ev_store_addr_o, lane);
      const uint64_t data = PayloadLane(dut_->ev_store_data_o, lane);
      const uint32_t size = (static_cast<uint32_t>(dut_->ev_store_size_o) >> (lane * 3)) & 0x7u;
      // HTIF command registers: the low word at `tohost`, the high word at
      // `tohost+4`. `RVMODEL_HALT_PASS` writes 1 then 0; `RVMODEL_HALT_FAIL`
      // writes 3 then 0; `RVMODEL_IO_WRITE_STR` writes the character then
      // 0x01010000 (device 1, command 1). A command with device 0 is the exit
      // protocol; a device command is console output and does not end the run.
      if (addr == tohost_addr_) {
        if (size == 8) {
          ConsiderExit(data & 0xffffffffull, (data >> 32) & 0xffffffffull);
        } else {
          pending_low_ = data & 0xffffffffull;
        }
      } else if (addr == tohost_addr_ + 4) {
        ConsiderExit(pending_low_, data & 0xffffffffull);
      }
    }
    if (dut_->o_unsupported_o != 0) saw_unsupported_ = true;
    if (std::getenv("MOSAIC_ACT_DEBUG") != nullptr && dut_->o_stopped_o != 0 &&
        !debug_stopped_) {
      debug_stopped_ = true;
      std::printf("  [stop] cycle=%llu deliver_pc=%s deliver_bits=%s "
                  "unsupported=%u illegal=%u rob=%u\n",
                  static_cast<unsigned long long>(cycles_),
                  U64(dut_->o_dbg_deliver_pc_o).c_str(),
                  mosaic::Hex(static_cast<uint32_t>(dut_->o_dbg_deliver_bits_o), 8).c_str(),
                  static_cast<unsigned>(dut_->o_unsupported_o),
                  static_cast<unsigned>(dut_->o_illegal_o),
                  static_cast<unsigned>(dut_->o_rob_occupied_o));
    }
    const bool progressed = (dut_->o_commit_o != last_commit_) ||
                            (dut_->o_wb_pub_valid_o != 0) ||
                            (dut_->o_dbg_alloc_ctr_o != last_alloc_);
    last_commit_ = dut_->o_commit_o;
    last_alloc_ = dut_->o_dbg_alloc_ctr_o;
    if (progressed) last_progress_ = cycles_;
  }

  // The HTIF command the two tohost words spell: device and command in the top
  // 16 bits, payload below. Device 0 command 0 is the exit protocol; any other
  // device is console output, which does not end the run.
  void ConsiderExit(uint64_t low, uint64_t high) {
    if (exit_seen_) return;
    if (high != 0) {
      // A console command: device in the high word, payload (the character) in
      // the low word. Kept so a failing test's own diagnostic is evidence.
      const uint8_t ch = static_cast<uint8_t>(low & 0xff);
      if (console_text_.size() < 4000 && ch != 0) console_text_.push_back(ch);
      ++console_chars_;
      pending_low_ = 0;
      return;
    }
    if (low != 0) {
      exit_seen_ = true;
      exit_value_ = low;
    }
  }

  void Cycle(bool rst, Imem* imem, DataMem* dmem) {
    dut_->rst = rst ? 1 : 0;
    dut_->imem_req_ready_i = 1;
    if (imem->HasResponse()) {
      const Imem::Request& r = imem->Response();
      dut_->imem_rsp_valid_i = 1;
      dut_->imem_rsp_rdata_i = static_cast<uint32_t>(imem->ResponseWord());
      dut_->imem_rsp_fault_i = 0;
      dut_->imem_rsp_id_i = r.id;
      dut_->imem_rsp_epoch_i = r.epoch;
      dut_->imem_rsp_len_i = 4;
    } else {
      dut_->imem_rsp_valid_i = 0;
      dut_->imem_rsp_rdata_i = 0;
      dut_->imem_rsp_fault_i = 0;
      dut_->imem_rsp_id_i = 0;
      dut_->imem_rsp_epoch_i = 0;
      dut_->imem_rsp_len_i = 0;
    }

    dut_->dmem_req_ready_i = 1;
    if (dmem->HasResponse()) {
      const DataMem::Rsp& r = dmem->CurrentResponse();
      dut_->dmem_rsp_valid_i = 1;
      dut_->dmem_rsp_rdata_i = r.rdata;
      dut_->dmem_rsp_fault_i = r.fault ? 1 : 0;
    } else {
      dut_->dmem_rsp_valid_i = 0;
      dut_->dmem_rsp_rdata_i = 0;
      dut_->dmem_rsp_fault_i = 0;
    }

    // The second DUT and the interrupt inputs are not used by this case.
    dut_->arb_req_valid0_i = 0;
    dut_->arb_req_valid1_i = 0;
    dut_->arb_head_valid_i = 0;
    dut_->arb_head_retire_i = 0;
    dut_->irq_soft_i = 0;
    dut_->irq_timer_i = 0;
    dut_->irq_ext_i = 0;
    dut_->mtime_i = 0;

    dut_->eval();
    if (!rst) Observe();

    if (bus_reset_.MayAccept(rst, (dut_->imem_req_valid_o != 0) &&
                                      (dut_->imem_req_ready_i != 0))) {
      imem->Accept(dut_->imem_req_addr_o, dut_->imem_req_id_o, dut_->imem_req_epoch_o);
    }
    if (bus_reset_.MayDeliver(rst) && (dut_->imem_rsp_valid_i != 0) &&
        (dut_->imem_rsp_ready_o != 0)) {
      imem->PopResponse();
    }
    imem->Advance();

    if (bus_reset_.MayAccept(rst, (dut_->dmem_req_valid_o != 0) &&
                                      (dut_->dmem_req_ready_i != 0))) {
      DataMem::Request r;
      r.we = dut_->dmem_req_we_o != 0;
      r.addr = dut_->dmem_req_addr_o;
      r.size = dut_->dmem_req_size_o;
      r.wstrb = dut_->dmem_req_wstrb_o;
      r.wdata = dut_->dmem_req_wdata_o;
      dmem->Accept(r, cycles_);
      if (r.we) {
        // The endpoint's payload is the aligned doubleword the address selects,
        // so the store is applied to the same window the data memory applies it
        // to, and the fetch image sees the bytes the program wrote.
        const uint64_t base = r.addr & ~UINT64_C(7);
        for (unsigned i = 0; i < 8; ++i) {
          if (((r.wstrb >> i) & 1u) != 0u) {
            bytes_[base + i] = static_cast<uint8_t>((r.wdata >> (8 * i)) & 0xff);
          }
        }
      }
    }
    if (bus_reset_.MayDeliver(rst) && (dut_->dmem_rsp_valid_i != 0) &&
        (dut_->dmem_rsp_ready_o != 0)) {
      dmem->PopResponse();
    }
    dmem->Advance();

    dut_->clk = 0;
    dut_->eval();
    dut_->clk = 1;
    dut_->eval();
    dut_->clk = 0;
    dut_->eval();
    ++cycles_;
  }

  Vmosaic_core_tb* dut_;
  // The reset-traffic rule (V-010, sim/common/bus_reset_gate.h): while reset
  // is asserted this model accepts nothing, so no reset-time response can be
  // queued ahead of a fresh post-reset one.
  mosaic::BusResetGate bus_reset_;
  Geometry g_;
  uint64_t cycles_ = 0;
  uint64_t last_commit_ = 0;
  uint64_t last_alloc_ = 0;
  uint64_t last_progress_ = 0;
  uint64_t stop_pc_ = 0;
  uint32_t stop_bits_ = 0;
  uint64_t stop_cycle_ = 0;
  bool saw_unsupported_ = false;
  bool exit_seen_ = false;
  uint64_t exit_value_ = 0;
  uint64_t pending_low_ = 0;
  uint64_t console_chars_ = 0;
  std::string console_text_;
  uint64_t tohost_addr_ = 0;
  uint64_t last_trap_cause_ = 0;
  uint64_t last_trap_pc_ = 0;
  uint64_t last_trap_tval_ = 0;
  uint64_t debug_traps_ = 0;
  bool debug_stopped_ = false;
  std::vector<Delivery> delivered_;
  std::set<uint64_t> retired_pcs_;
  std::map<uint64_t, uint8_t> bytes_;
  bool delivery_tracking_overflowed_ = false;
};

// ============================================================================
// The generation manifest and the repository root
// ============================================================================
// The registered run (no `--image`) reads the manifest `tools/run_act_dut.py`
// writes, so `make unit` executes the whole generated suite rather than a single
// file. The manifest names the ELF root and the count the generator produced; the
// driver enumerates the root itself, so the count and the set are cross-checked
// rather than one being trusted.
struct ElfCase {
  std::string suite;
  std::string path;
};

struct Manifest {
  uint64_t count = 0;
  std::string elf_root;
  std::string act_commit = "?";
  std::string config = "?";
};

bool ReadWholeFile(const std::string& path, std::string* out) {
  std::ifstream in(path, std::ios::binary);
  if (!in) return false;
  std::ostringstream buffer;
  buffer << in.rdbuf();
  *out = buffer.str();
  return true;
}

bool JsonString(const std::string& text, const std::string& key, std::string* out) {
  const std::string needle = "\"" + key + "\"";
  const size_t at = text.find(needle);
  if (at == std::string::npos) return false;
  size_t pos = text.find(':', at + needle.size());
  if (pos == std::string::npos) return false;
  ++pos;
  while (pos < text.size() && (text[pos] == ' ' || text[pos] == '\t' ||
                               text[pos] == '\n' || text[pos] == '\r')) {
    ++pos;
  }
  if (pos >= text.size() || text[pos] != '"') return false;
  ++pos;
  std::string value;
  while (pos < text.size() && text[pos] != '"') {
    if (text[pos] == '\\' && pos + 1 < text.size()) ++pos;
    value.push_back(text[pos++]);
  }
  *out = value;
  return true;
}

bool JsonUint(const std::string& text, const std::string& key, uint64_t* out) {
  const std::string needle = "\"" + key + "\"";
  const size_t at = text.find(needle);
  if (at == std::string::npos) return false;
  size_t pos = text.find(':', at + needle.size());
  if (pos == std::string::npos) return false;
  ++pos;
  while (pos < text.size() && (text[pos] == ' ' || text[pos] == '\t' ||
                               text[pos] == '\n' || text[pos] == '\r')) {
    ++pos;
  }
  size_t end = pos;
  while (end < text.size() && std::isdigit(static_cast<unsigned char>(text[end]))) ++end;
  if (end == pos) return false;
  *out = std::strtoull(text.substr(pos, end - pos).c_str(), nullptr, 10);
  return true;
}

std::string FindRepoRoot() {
  std::string dir = ".";
  for (int depth = 0; depth < 8; ++depth) {
    std::ifstream probe(dir + "/config/profiles/p1.json");
    if (probe) {
      char resolved[4096];
      if (realpath(dir.c_str(), resolved) != nullptr) return std::string(resolved);
      return dir;
    }
    dir += "/..";
  }
  Fail("setup", "cannot find the repository root: no config/profiles/p1.json above the "
                "working directory");
}

bool ReadManifest(const std::string& path, Manifest* out, std::string* why) {
  std::string text;
  if (!ReadWholeFile(path, &text)) {
    *why = "no ACT4 manifest at " + path +
           "; run `python3 tools/run_act_dut.py` to generate the suite and write it";
    return false;
  }
  if (!JsonUint(text, "count", &out->count) || out->count == 0) {
    *why = "the ACT4 manifest " + path + " has no positive `count`";
    return false;
  }
  if (!JsonString(text, "elf_root", &out->elf_root) || out->elf_root.empty()) {
    *why = "the ACT4 manifest " + path + " has no `elf_root`";
    return false;
  }
  JsonString(text, "act_commit", &out->act_commit);
  JsonString(text, "config", &out->config);
  return true;
}

std::vector<ElfCase> EnumerateElfs(const std::string& root) {
  std::vector<ElfCase> out;
  std::string command = "find " + root + " -type f -name '*.elf' | sort";
  std::FILE* pipe = popen(command.c_str(), "r");
  if (pipe == nullptr) return out;
  char line[4096];
  while (std::fgets(line, sizeof(line), pipe) != nullptr) {
    std::string path(line);
    while (!path.empty() && (path.back() == '\n' || path.back() == '\r')) path.pop_back();
    if (path.empty()) continue;
    const size_t slash = path.find_last_of('/');
    const std::string dir = (slash == std::string::npos) ? "" : path.substr(0, slash);
    const size_t slash2 = dir.find_last_of('/');
    const std::string suite = (slash2 == std::string::npos) ? dir : dir.substr(slash2 + 1);
    out.push_back(ElfCase{suite, path});
  }
  pclose(pipe);
  return out;
}

}  // namespace

int main(int argc, char** argv) {
  mosaic::Options options;
  std::string error;
  if (!mosaic::Options::Parse(argc, argv, &options, &error)) {
    std::fprintf(stderr, "%s\n", error.c_str());
    return mosaic::kExitUsage;
  }
  Verilated::commandArgs(argc, argv);

  mosaic::Reporter reporter(options,
                            std::string("Verilator ") + Verilated::productVersion());
  Vmosaic_core_tb dut;

  try {
    dut.clk = 0;
    dut.rst = 0;
    dut.eval();
    const Geometry geometry = ReadGeometry(&dut);
    if (geometry.xlen != 64) Fail("geometry", "the profile is not 64-bit");

    // The set to run: one image named on the command line, or the generated
    // suite the manifest describes.
    std::vector<ElfCase> entries;
    uint64_t generated = 0;
    std::string commit = "?";
    std::string config = "?";
    if (!options.image.empty()) {
      entries.push_back(ElfCase{"(single)", options.image});
      generated = 1;
    } else {
      const std::string repo = FindRepoRoot();
      const std::string manifest_path =
          repo + "/tests/act4/mosaic-p1/elf_manifest.json";
      Manifest manifest;
      std::string why;
      if (!ReadManifest(manifest_path, &manifest, &why)) Fail("manifest", why);
      entries = EnumerateElfs(manifest.elf_root);
      generated = manifest.count;
      commit = manifest.act_commit;
      config = manifest.config;
      std::printf("ACT4 manifest: generated=%llu enumerated=%zu elf_root=%s "
                  "act_commit=%s config=%s\n",
                  static_cast<unsigned long long>(generated), entries.size(),
                  manifest.elf_root.c_str(), commit.c_str(), config.c_str());
    }

    uint64_t run = 0;
    uint64_t passed = 0;
    uint64_t failed = 0;
    std::string first_fail;
    for (const ElfCase& entry : entries) {
      Runner runner(&dut, geometry);
      const RunRecord record = runner.Run(entry.path, options.max_cycles);
      const std::string name = entry.path;
      std::printf("ACT-ELF %-40s suite=%-9s value=%s cycles=%llu retires=%llu "
                  "traps=%llu console=%llu status=%s\n",
                  name.c_str(), entry.suite.c_str(),
                  U64(record.tohost_value).c_str(),
                  static_cast<unsigned long long>(record.cycles),
                  static_cast<unsigned long long>(record.retires),
                  static_cast<unsigned long long>(record.traps_taken),
                  static_cast<unsigned long long>(record.console_chars),
                  StatusName(record.status));
      ++run;
      const bool ok = (record.status == RunStatus::kPass);
      if (ok) {
        ++passed;
      } else {
        ++failed;
        if (first_fail.empty()) first_fail = name;
        std::printf("  first failure: status=%s value=%s stop_pc=%s stop_word=%s "
                    "last_trap pc=%s cause=%s tval=%s note=%s\n",
                    StatusName(record.status), U64(record.tohost_value).c_str(),
                    U64(record.stop_pc).c_str(),
                    mosaic::Hex(record.stop_bits, 8).c_str(),
                    U64(record.last_trap_pc).c_str(),
                    U64(record.last_trap_cause).c_str(),
                    U64(record.last_trap_tval).c_str(), record.note.c_str());
        if (!record.console_text.empty()) {
          std::printf("  console: %s\n", record.console_text.c_str());
        }
      }
      if (!record.signature.empty()) {
        std::printf("  signature (%zu words):", record.signature.size());
        for (uint64_t w : record.signature) std::printf(" %s", U64(w).c_str());
        std::printf("\n");
      }
      reporter.Check(ok, "ELF " + entry.suite + "/" +
                             name.substr(name.find_last_of('/') + 1) +
                             " passed its own self-check (status " +
                             StatusName(record.status) + ")");
    }

    reporter.Check(generated == entries.size(),
                   "the generated count equals the enumerated set (" +
                       Dec(generated) + " vs " + Dec(entries.size()) + ")");
    reporter.Check(run == generated,
                   "every generated ELF ran (" + Dec(run) + " of " + Dec(generated) + ")");
    reporter.Check(failed == 0, "no ELF failed (" + Dec(failed) + " failed)");

    std::string detail = "applicable=" + Dec(generated) + " generated=" +
                         Dec(generated) + " run=" + Dec(run) + " passed=" +
                         Dec(passed) + " failed=" + Dec(failed);
    detail += " act_commit=" + commit + " config=" + config;
    if (!first_fail.empty()) detail += " first_fail=" + first_fail;
    const std::string verdict = (reporter.failures() == 0) ? "PASS" : "FAIL";
    return reporter.Finish(verdict, detail);
  } catch (const Failure& failure) {
    reporter.Mismatch(failure.what, "a runnable ACT4 suite", "setup failure");
    return reporter.Finish("BLOCKED", failure.what);
  }
}
