#!/usr/bin/env python3
"""Prove the RTL is synthesisable with a generic Yosys run.

    python3 tools/synth_check.py --profile p0

This is a portability smoke test, not a timing or area claim: it elaborates the
same source a vendor tool would see, with no vendor primitives available, and
fails if anything a real tool would choke on shows up. Specifically it fails on:

  * a latch (``$dlatch``) inferred from an incomplete combinational block;
  * a hierarchy/elaboration error, an undriven or multiply-driven wire, or an
    unconnected port that matters;
  * a memory with no defined read behaviour;
  * anything Yosys cannot elaborate at all.

Exits 0 only if the design elaborates cleanly and contains no latches.
"""

from __future__ import annotations

import argparse
import os
import re
import subprocess
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

from mosaic import config_check  # noqa: E402

REPO_ROOT = config_check.REPO_ROOT
RTL_ROOT = os.path.join(REPO_ROOT, "rtl")


def collect_sources() -> list:
    sources = []
    for base, _dirs, files in os.walk(RTL_ROOT):
        if os.sep + "build" in base:
            continue
        for name in sorted(files):
            if name.endswith(".sv") or name.endswith(".v"):
                sources.append(os.path.join(base, name))
    return sorted(sources)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--profile", default="p0")
    parser.add_argument("--top", default="mosaic_top")
    parser.add_argument("--keep", action="store_true", help="keep the generated script")
    args = parser.parse_args()

    sources = collect_sources()
    if not sources:
        print("synth-check: no RTL sources under rtl/ yet; nothing to elaborate", file=sys.stderr)
        return 1

    build_dir = os.path.join(REPO_ROOT, "build", args.profile, "synth")
    os.makedirs(build_dir, exist_ok=True)
    script_path = os.path.join(build_dir, "generic.ys")
    log_path = os.path.join(build_dir, "yosys.log")

    rel = lambda p: os.path.relpath(p, REPO_ROOT)  # noqa: E731
    lines = [
        "# Generated by tools/synth_check.py --profile %s" % args.profile,
        "read_verilog -sv -I%s -I%s -I%s" % (
            os.path.join(REPO_ROOT, "build", args.profile, "rtl"),
            os.path.join(RTL_ROOT, "common"),
            os.path.join(RTL_ROOT, "core"),
        ),
    ]
    lines += [rel(source) for source in sources]
    lines += [
        "",
        "hierarchy -check -top %s" % args.top,
        "proc",
        "opt_expr",
        "opt_clean",
        "check -assert",
        "memory -nomap",
        "opt -full",
        "stat",
        "",
        "# A latch is never acceptable in this design: every combinational block",
        "# must assign all of its outputs on every path.",
        "select -assert-none t:$dlatch",
        "",
    ]
    with open(script_path, "w") as handle:
        handle.write("\n".join(lines))

    result = subprocess.run(["yosys", "-q", "-s", script_path],
                            cwd=REPO_ROOT, stdout=subprocess.PIPE, stderr=subprocess.STDOUT)
    log = result.stdout.decode("utf-8", "replace")
    with open(log_path, "w") as handle:
        handle.write(log)

    if result.returncode != 0:
        print("synth-check: Yosys failed for profile %s" % args.profile, file=sys.stderr)
        tail = [line for line in log.splitlines() if "rror" in line or "arning" in line]
        for line in tail[-20:]:
            print("  " + line, file=sys.stderr)
        print("  full log: %s" % os.path.relpath(log_path, REPO_ROOT), file=sys.stderr)
        return 1

    latches = re.findall(r"^\s+\$dlatch", log, re.MULTILINE)
    if latches:
        print("synth-check: %d latch(es) inferred; combinational blocks are incomplete"
              % len(latches), file=sys.stderr)
        return 1

    print("synth-check: profile %s elaborates cleanly, %d source file(s), no latches"
          % (args.profile, len(sources)))
    print("  log: %s" % os.path.relpath(log_path, REPO_ROOT))
    if not args.keep and os.path.exists(script_path):
        os.remove(script_path)
    return 0


if __name__ == "__main__":
    sys.exit(main())