#!/usr/bin/env python3
"""Prove the RTL is synthesisable with a generic Yosys run (V-series portability check).

    python3 tools/synth_check.py --profile p0

This is a portability smoke test, not a timing or area claim. It elaborates the same
source a vendor tool would see, with no vendor primitive available, and fails on:

  * a hierarchy or elaboration error, an undriven or multiply-driven wire, or an
    unconnected port that matters (`check -assert`);
  * a latch inferred from an incomplete combinational block (`select -assert-none`);
  * anything Yosys cannot elaborate at all.

Two accommodations are made for Yosys, both deliberate and both printed on every run
so they can never be mistaken for the shipped source:

1. **Packages are read before the files that use them.** Yosys processes `read_verilog`
   files in order, so a module referencing a type declared later fails to elaborate.
2. **`import` statements are stripped into a regenerated scratch copy.** Yosys 0.69
   parses SystemVerilog packages and fully-qualified references (`p::X`) but rejects
   `import` outright. The RTL uses `import mosaic_pkg::*;` because Verilator and
   slang require it. Stripping is safe only because every package reference in this
   design is fully qualified, so no name becomes unreachable — and if that ever stops
   being true, Yosys fails with an unresolved identifier rather than silently
   elaborating something different. The shipped RTL is never modified.

Exit status is 0 only if the design elaborates cleanly and contains no latches.
"""

from __future__ import annotations

import argparse
import os
import re
import shutil
import subprocess
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

from mosaic import config_check  # noqa: E402

REPO_ROOT = config_check.REPO_ROOT
RTL_ROOT = os.path.join(REPO_ROOT, "rtl")

MODULE_RE = re.compile(r"^\s*module\s+([A-Za-z_][A-Za-z0-9_$]*)", re.MULTILINE)
IMPORT_RE = re.compile(r"^\s*import\s+\w+::\*\s*;.*$", re.MULTILINE)


def collect_sources() -> list:
    sources = []
    for base, dirs, files in os.walk(RTL_ROOT):
        dirs[:] = [d for d in dirs if d != "build"]
        for name in sorted(files):
            if name.endswith((".sv", ".v")):
                sources.append(os.path.join(base, name))
    return sorted(sources)


def prepare_scratch(sources: list, scratch: str) -> int:
    """Copy the RTL, stripping `import` lines Yosys cannot parse.

    Returns how many lines were removed, which the caller reports so the
    accommodation is visible rather than silent.
    """
    if os.path.isdir(scratch):
        shutil.rmtree(scratch)
    removed = 0
    for source in sources:
        relative = os.path.relpath(source, REPO_ROOT)
        target = os.path.join(scratch, relative)
        os.makedirs(os.path.dirname(target), exist_ok=True)
        with open(source, "r", errors="replace") as handle:
            text = handle.read()
        stripped, count = IMPORT_RE.subn("", text)
        removed += count
        with open(target, "w") as handle:
            handle.write(stripped)
    return removed


def choose_top(sources: list) -> str:
    """Pick the largest single-module RTL file as the synthesis top.

    Naming a top that does not exist makes this check meaningless: `hierarchy -check`
    would fail, but for a reason that looks like a design problem rather than a
    configuration one. The largest real module is an actual design object and gives
    the most demanding elaboration currently available.
    """
    best_name = None
    best_size = -1
    for source in sources:
        with open(source, "r", errors="replace") as handle:
            text = handle.read()
        names = MODULE_RE.findall(text)
        if len(names) != 1:
            continue  # a package, or several modules in one file
        size = os.path.getsize(source)
        if size > best_size:
            best_size = size
            best_name = names[0]
    if best_name is None:
        raise SystemExit("synth-check: no single-module RTL file found to use as a top")
    return best_name


def write_script(profile: str, top: str, scratch: str, script_path: str) -> None:
    include_dirs = " ".join(
        "-I" + path for path in (
            os.path.join(REPO_ROOT, "build", profile, "rtl"),
            os.path.join(RTL_ROOT, "common"),
            os.path.join(RTL_ROOT, "core"),
        )
    )

    sources = []
    for base, _dirs, files in os.walk(scratch):
        for name in sorted(files):
            if name.endswith((".sv", ".v")):
                sources.append(os.path.join(base, name))
    sources.sort()
    # Packages first: see the module docstring.
    packages = [s for s in sources if os.path.basename(s) == "mosaic_pkg.sv"]
    modules = [s for s in sources if s not in packages]
    file_list = " ".join(os.path.relpath(s, REPO_ROOT) for s in packages + modules)

    lines = [
        "# Generated by tools/synth_check.py --profile %s" % profile,
        "# Sources are on the SAME LINE as read_verilog: Yosys parses one command per",
        "# line and reports 'No filename given' when the file list is split across lines.",
        "read_verilog -sv %s %s" % (include_dirs, file_list),
        "",
        "hierarchy -check -top %s" % top,
        "proc",
        "opt_expr",
        "opt_clean",
        "check -assert",
        "memory -nomap",
        "opt -full",
        "stat",
        "",
        "# A latch is never acceptable: every combinational block must assign all of",
        "# its outputs on every path.",
        "select -assert-none t:$dlatch",
        "",
    ]
    with open(script_path, "w") as handle:
        handle.write("\n".join(lines))


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--profile", default="p0")
    parser.add_argument("--allow-blocked", action="store_true",
                        help="treat exit 2 (tool limitation) as success, for use where "
                             "a generic synthesis pass is informative but not gating")
    parser.add_argument("--top", default=None,
                        help="top module; defaults to the largest single-module RTL file")
    args = parser.parse_args()

    sources = collect_sources()
    if not sources:
        print("synth-check: no RTL sources under rtl/ yet; nothing to elaborate",
              file=sys.stderr)
        return 1

    build_dir = os.path.join(REPO_ROOT, "build", args.profile, "synth")
    os.makedirs(build_dir, exist_ok=True)
    script_path = os.path.join(build_dir, "generic.ys")
    log_path = os.path.join(build_dir, "yosys.log")
    scratch = os.path.join(build_dir, "yosys-src")

    removed = prepare_scratch(sources, scratch)
    top = args.top or choose_top(sources)
    write_script(args.profile, top, scratch, script_path)

    print("  top: %s" % top)
    print("  note: Yosys 0.69 cannot parse `import`; %d such line(s) are stripped into a "
          "scratch copy regenerated on every run. The shipped RTL is unmodified and "
          "every package reference is fully qualified." % removed)

    result = subprocess.run(["yosys", "-q", "-s", script_path], cwd=REPO_ROOT,
                            stdout=subprocess.PIPE, stderr=subprocess.STDOUT)
    log = result.stdout.decode("utf-8", "replace")
    with open(log_path, "w") as handle:
        handle.write(log)

    if result.returncode != 0 and getattr(args, "allow_blocked", False) and \
            "unexpected ':'" in log:
        print("synth-check: BLOCKED (allowed) -- Yosys cannot parse assignment patterns")
        return 0

    if result.returncode != 0:
        errors = [line for line in log.splitlines() if "ERROR" in line]
        # Yosys 0.69 cannot parse SystemVerilog assignment patterns (`'{a: 1'b1}`).
        # That is a limitation of the tool, not of the RTL, and it is *not* worked
        # around: rewriting idiomatic, readable SystemVerilog into something one
        # open-source tool can parse would trade portability we actually have for
        # coverage of a tool we do not. Vendor synthesis tools do support
        # assignment patterns. The limitation is reported so the gap is visible.
        if any("unexpected ':'" in line for line in errors):
            print("synth-check: BLOCKED for profile %s -- Yosys 0.69 cannot parse "
                  "SystemVerilog assignment patterns" % args.profile, file=sys.stderr)
            for line in errors[-3:]:
                print("  " + line, file=sys.stderr)
            print("  This is a tool limitation, not an RTL defect. The RTL lints clean "
                  "under Verilator -Wall and parses and type-checks under slang; the "
                  "same constructs are supported by vendor synthesis tools.", file=sys.stderr)
            print("  full log: %s" % os.path.relpath(log_path, REPO_ROOT), file=sys.stderr)
            return 2

        print("synth-check: Yosys failed for profile %s" % args.profile, file=sys.stderr)
        for line in errors[-10:]:
            print("  " + line, file=sys.stderr)
        print("  full log: %s" % os.path.relpath(log_path, REPO_ROOT), file=sys.stderr)
        return 1

    latches = re.findall(r"^\s+\$dlatch", log, re.MULTILINE)
    if latches:
        print("synth-check: %d latch(es) inferred; combinational blocks are incomplete"
              % len(latches), file=sys.stderr)
        return 1

    print("synth-check: profile %s elaborates cleanly as %s, %d source file(s), no latches"
          % (args.profile, top, len(sources)))
    print("  log: %s" % os.path.relpath(log_path, REPO_ROOT))
    return 0


if __name__ == "__main__":
    sys.exit(main())